name: Example

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - example*

jobs:
  uv-example:
    # see: https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi
    name: python
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDCトークンを使うために必要
      contents: read
    environment: testpypi

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      # v6だと nektos/act でエラーになる。shim不足

      - name: Set up Python
        run: uv python install

      - name: Build
        run: uv build

      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl src/h4_hello/main.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz src/h4_hello/main.py

      - name: Publish to TestPyPI
        run: uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always

      # - name: Publish
      #   run: uv publish
